-- Generated by CSharp.lua Compiler
local System = System
local Linq = System.Linq.Enumerable
local SlipeMtaDefinitions
local SlipeServerVehicles
local SlipeSharedElements
local SlipeSharedVehicles
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeServerVehicles = Slipe.Server.Vehicles
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedVehicles = Slipe.Shared.Vehicles
end)
System.namespace("Slipe.Server.Vehicles", function (namespace)
  -- <summary>
  -- Class for all other road vehicle models
  -- </summary>
  namespace.class("VehicleModel", function (namespace)
    local getHandling, getVehicles, FromName, FromId, class, __ctor__
    namespace.class("Bikes", function (namespace)
      local getBf400, getFaggio, getFcr900, getFreeway, getHpv1000, getNrg500, getPcj600, getPizzaboy, 
      getSanchez, getWayfarer, getQuadbike, getBike, getBmx, getMountainbike
      getBf400 = function ()
        return SlipeServerVehicles.VehicleModel(581)
      end
      getFaggio = function ()
        return SlipeServerVehicles.VehicleModel(462)
      end
      getFcr900 = function ()
        return SlipeServerVehicles.VehicleModel(521)
      end
      getFreeway = function ()
        return SlipeServerVehicles.VehicleModel(463)
      end
      getHpv1000 = function ()
        return SlipeServerVehicles.VehicleModel(523)
      end
      getNrg500 = function ()
        return SlipeServerVehicles.VehicleModel(522)
      end
      getPcj600 = function ()
        return SlipeServerVehicles.VehicleModel(461)
      end
      getPizzaboy = function ()
        return SlipeServerVehicles.VehicleModel(448)
      end
      getSanchez = function ()
        return SlipeServerVehicles.VehicleModel(468)
      end
      getWayfarer = function ()
        return SlipeServerVehicles.VehicleModel(586)
      end
      getQuadbike = function ()
        return SlipeServerVehicles.VehicleModel(471)
      end
      getBike = function ()
        return SlipeServerVehicles.VehicleModel(509)
      end
      getBmx = function ()
        return SlipeServerVehicles.VehicleModel(481)
      end
      getMountainbike = function ()
        return SlipeServerVehicles.VehicleModel(510)
      end
      return {
        getBf400 = getBf400,
        getFaggio = getFaggio,
        getFcr900 = getFcr900,
        getFreeway = getFreeway,
        getHpv1000 = getHpv1000,
        getNrg500 = getNrg500,
        getPcj600 = getPcj600,
        getPizzaboy = getPizzaboy,
        getSanchez = getSanchez,
        getWayfarer = getWayfarer,
        getQuadbike = getQuadbike,
        getBike = getBike,
        getBmx = getBmx,
        getMountainbike = getMountainbike
      }
    end)
    namespace.class("Cars", function (namespace)
      local getAlpha, getBanshee, getBuffalo, getBullet, getCheetah, getComet, getElegy, getEuros, 
      getFlash, getInfernus, getJester, getPhoenix, getSultan, getSupergt, getTurismo, getUranus, 
      getWindsor, getZr350, getBlade, getBroadway, getBuccaneer, getEsperanto, getRemington, getSavanna, 
      getSlamvan, getTornado, getVoodoo, getBlistacompact, getBravura, getCadrona, getClover, getFeltzer, 
      getFortune, getHermes, getHustler, getMajestic, getManana, getPrevion, getSabre, getStallion, 
      getTampa, getVirgo, getAdmiral, getElegant, getEmperor, getGlendale, getGreenwood, getIntruder, 
      getMerit, getNebula, getOceanic, getPremier, getPrimo, getSentinel, getStafford, getStretch, 
      getSunrise, getTahoma, getVincent, getWashington, getWillard, getAmbulance, getBarracks, getEnforcer, 
      getFbirancher, getFbitruck, getFiretruckladder, getPolicecarls, getPolicecarlv, getPolicecarsf, getPoliceranger, getCementtruck, 
      getDft30, getDozer, getDumper, getDune, getFlatbed, getForklift, getLinerunner, getPacker, 
      getRoadtrain, getSweeper, getTanker, getTowtruck, getTrashmaster, getUtilityvan, getBenson, getBlackboxville, 
      getBobcat, getBoxville, getMule, getPicador, getSadler, getSecuricar, getWalton, getYankee, 
      getYosemite, getBerkleysrcvan, getBurrito, getCamper, getJourney, getMoonbeam, getNewsvan, getPony, 
      getRumpo, getBaggage, getBandito, getBfinjection, getBloodringbanger, getBus, getCaddy, getCoach, 
      getCombineharvester, getHotdog, getHotknife, getHotringracer1, getHotringracer2, getHotringracer3, getMonster1, getMonster2, 
      getMonster3, getMower, getMrwhoopee, getKart, getTractor, getTug, getVortex, getRcBandit, 
      getRcFlowerpot, getRcTiger, getClub, getHuntley, getLandstalker, getMesa, getPatriot, getPerennial, 
      getRancher, getRegina, getRomero, getSandking, getSolair, getStratum
      getAlpha = function ()
        return SlipeServerVehicles.VehicleModel(602)
      end
      getBanshee = function ()
        return SlipeServerVehicles.VehicleModel(429)
      end
      getBuffalo = function ()
        return SlipeServerVehicles.VehicleModel(402)
      end
      getBullet = function ()
        return SlipeServerVehicles.VehicleModel(541)
      end
      getCheetah = function ()
        return SlipeServerVehicles.VehicleModel(415)
      end
      getComet = function ()
        return SlipeServerVehicles.VehicleModel(480)
      end
      getElegy = function ()
        return SlipeServerVehicles.VehicleModel(562)
      end
      getEuros = function ()
        return SlipeServerVehicles.VehicleModel(587)
      end
      getFlash = function ()
        return SlipeServerVehicles.VehicleModel(565)
      end
      getInfernus = function ()
        return SlipeServerVehicles.VehicleModel(411)
      end
      getJester = function ()
        return SlipeServerVehicles.VehicleModel(559)
      end
      getPhoenix = function ()
        return SlipeServerVehicles.VehicleModel(603)
      end
      getSultan = function ()
        return SlipeServerVehicles.VehicleModel(560)
      end
      getSupergt = function ()
        return SlipeServerVehicles.VehicleModel(506)
      end
      getTurismo = function ()
        return SlipeServerVehicles.VehicleModel(451)
      end
      getUranus = function ()
        return SlipeServerVehicles.VehicleModel(558)
      end
      getWindsor = function ()
        return SlipeServerVehicles.VehicleModel(555)
      end
      getZr350 = function ()
        return SlipeServerVehicles.VehicleModel(477)
      end
      getBlade = function ()
        return SlipeServerVehicles.VehicleModel(536)
      end
      getBroadway = function ()
        return SlipeServerVehicles.VehicleModel(575)
      end
      getBuccaneer = function ()
        return SlipeServerVehicles.VehicleModel(518)
      end
      getEsperanto = function ()
        return SlipeServerVehicles.VehicleModel(419)
      end
      getRemington = function ()
        return SlipeServerVehicles.VehicleModel(534)
      end
      getSavanna = function ()
        return SlipeServerVehicles.VehicleModel(567)
      end
      getSlamvan = function ()
        return SlipeServerVehicles.VehicleModel(535)
      end
      getTornado = function ()
        return SlipeServerVehicles.VehicleModel(576)
      end
      getVoodoo = function ()
        return SlipeServerVehicles.VehicleModel(412)
      end
      getBlistacompact = function ()
        return SlipeServerVehicles.VehicleModel(496)
      end
      getBravura = function ()
        return SlipeServerVehicles.VehicleModel(401)
      end
      getCadrona = function ()
        return SlipeServerVehicles.VehicleModel(527)
      end
      getClover = function ()
        return SlipeServerVehicles.VehicleModel(542)
      end
      getFeltzer = function ()
        return SlipeServerVehicles.VehicleModel(533)
      end
      getFortune = function ()
        return SlipeServerVehicles.VehicleModel(526)
      end
      getHermes = function ()
        return SlipeServerVehicles.VehicleModel(474)
      end
      getHustler = function ()
        return SlipeServerVehicles.VehicleModel(545)
      end
      getMajestic = function ()
        return SlipeServerVehicles.VehicleModel(517)
      end
      getManana = function ()
        return SlipeServerVehicles.VehicleModel(410)
      end
      getPrevion = function ()
        return SlipeServerVehicles.VehicleModel(436)
      end
      getSabre = function ()
        return SlipeServerVehicles.VehicleModel(475)
      end
      getStallion = function ()
        return SlipeServerVehicles.VehicleModel(439)
      end
      getTampa = function ()
        return SlipeServerVehicles.VehicleModel(549)
      end
      getVirgo = function ()
        return SlipeServerVehicles.VehicleModel(491)
      end
      getAdmiral = function ()
        return SlipeServerVehicles.VehicleModel(445)
      end
      getElegant = function ()
        return SlipeServerVehicles.VehicleModel(507)
      end
      getEmperor = function ()
        return SlipeServerVehicles.VehicleModel(585)
      end
      getGlendale = function ()
        return SlipeServerVehicles.VehicleModel(466)
      end
      getGreenwood = function ()
        return SlipeServerVehicles.VehicleModel(492)
      end
      getIntruder = function ()
        return SlipeServerVehicles.VehicleModel(546)
      end
      getMerit = function ()
        return SlipeServerVehicles.VehicleModel(551)
      end
      getNebula = function ()
        return SlipeServerVehicles.VehicleModel(516)
      end
      getOceanic = function ()
        return SlipeServerVehicles.VehicleModel(467)
      end
      getPremier = function ()
        return SlipeServerVehicles.VehicleModel(426)
      end
      getPrimo = function ()
        return SlipeServerVehicles.VehicleModel(547)
      end
      getSentinel = function ()
        return SlipeServerVehicles.VehicleModel(405)
      end
      getStafford = function ()
        return SlipeServerVehicles.VehicleModel(580)
      end
      getStretch = function ()
        return SlipeServerVehicles.VehicleModel(409)
      end
      getSunrise = function ()
        return SlipeServerVehicles.VehicleModel(550)
      end
      getTahoma = function ()
        return SlipeServerVehicles.VehicleModel(566)
      end
      getVincent = function ()
        return SlipeServerVehicles.VehicleModel(540)
      end
      getWashington = function ()
        return SlipeServerVehicles.VehicleModel(421)
      end
      getWillard = function ()
        return SlipeServerVehicles.VehicleModel(529)
      end
      getAmbulance = function ()
        return SlipeServerVehicles.VehicleModel(416)
      end
      getBarracks = function ()
        return SlipeServerVehicles.VehicleModel(433)
      end
      getEnforcer = function ()
        return SlipeServerVehicles.VehicleModel(427)
      end
      getFbirancher = function ()
        return SlipeServerVehicles.VehicleModel(490)
      end
      getFbitruck = function ()
        return SlipeServerVehicles.VehicleModel(528)
      end
      getFiretruckladder = function ()
        return SlipeServerVehicles.VehicleModel(544)
      end
      getPolicecarls = function ()
        return SlipeServerVehicles.VehicleModel(596)
      end
      getPolicecarlv = function ()
        return SlipeServerVehicles.VehicleModel(598)
      end
      getPolicecarsf = function ()
        return SlipeServerVehicles.VehicleModel(597)
      end
      getPoliceranger = function ()
        return SlipeServerVehicles.VehicleModel(599)
      end
      getCementtruck = function ()
        return SlipeServerVehicles.VehicleModel(524)
      end
      getDft30 = function ()
        return SlipeServerVehicles.VehicleModel(578)
      end
      getDozer = function ()
        return SlipeServerVehicles.VehicleModel(486)
      end
      getDumper = function ()
        return SlipeServerVehicles.VehicleModel(406)
      end
      getDune = function ()
        return SlipeServerVehicles.VehicleModel(573)
      end
      getFlatbed = function ()
        return SlipeServerVehicles.VehicleModel(455)
      end
      getForklift = function ()
        return SlipeServerVehicles.VehicleModel(530)
      end
      getLinerunner = function ()
        return SlipeServerVehicles.VehicleModel(403)
      end
      getPacker = function ()
        return SlipeServerVehicles.VehicleModel(443)
      end
      getRoadtrain = function ()
        return SlipeServerVehicles.VehicleModel(515)
      end
      getSweeper = function ()
        return SlipeServerVehicles.VehicleModel(574)
      end
      getTanker = function ()
        return SlipeServerVehicles.VehicleModel(514)
      end
      getTowtruck = function ()
        return SlipeServerVehicles.VehicleModel(525)
      end
      getTrashmaster = function ()
        return SlipeServerVehicles.VehicleModel(408)
      end
      getUtilityvan = function ()
        return SlipeServerVehicles.VehicleModel(552)
      end
      getBenson = function ()
        return SlipeServerVehicles.VehicleModel(499)
      end
      getBlackboxville = function ()
        return SlipeServerVehicles.VehicleModel(609)
      end
      getBobcat = function ()
        return SlipeServerVehicles.VehicleModel(422)
      end
      getBoxville = function ()
        return SlipeServerVehicles.VehicleModel(498)
      end
      getMule = function ()
        return SlipeServerVehicles.VehicleModel(414)
      end
      getPicador = function ()
        return SlipeServerVehicles.VehicleModel(600)
      end
      getSadler = function ()
        return SlipeServerVehicles.VehicleModel(543)
      end
      getSecuricar = function ()
        return SlipeServerVehicles.VehicleModel(428)
      end
      getWalton = function ()
        return SlipeServerVehicles.VehicleModel(478)
      end
      getYankee = function ()
        return SlipeServerVehicles.VehicleModel(456)
      end
      getYosemite = function ()
        return SlipeServerVehicles.VehicleModel(554)
      end
      getBerkleysrcvan = function ()
        return SlipeServerVehicles.VehicleModel(459)
      end
      getBurrito = function ()
        return SlipeServerVehicles.VehicleModel(482)
      end
      getCamper = function ()
        return SlipeServerVehicles.VehicleModel(483)
      end
      getJourney = function ()
        return SlipeServerVehicles.VehicleModel(508)
      end
      getMoonbeam = function ()
        return SlipeServerVehicles.VehicleModel(418)
      end
      getNewsvan = function ()
        return SlipeServerVehicles.VehicleModel(582)
      end
      getPony = function ()
        return SlipeServerVehicles.VehicleModel(413)
      end
      getRumpo = function ()
        return SlipeServerVehicles.VehicleModel(440)
      end
      getBaggage = function ()
        return SlipeServerVehicles.VehicleModel(485)
      end
      getBandito = function ()
        return SlipeServerVehicles.VehicleModel(568)
      end
      getBfinjection = function ()
        return SlipeServerVehicles.VehicleModel(424)
      end
      getBloodringbanger = function ()
        return SlipeServerVehicles.VehicleModel(504)
      end
      getBus = function ()
        return SlipeServerVehicles.VehicleModel(431)
      end
      getCaddy = function ()
        return SlipeServerVehicles.VehicleModel(457)
      end
      getCoach = function ()
        return SlipeServerVehicles.VehicleModel(437)
      end
      getCombineharvester = function ()
        return SlipeServerVehicles.VehicleModel(532)
      end
      getHotdog = function ()
        return SlipeServerVehicles.VehicleModel(588)
      end
      getHotknife = function ()
        return SlipeServerVehicles.VehicleModel(434)
      end
      getHotringracer1 = function ()
        return SlipeServerVehicles.VehicleModel(494)
      end
      getHotringracer2 = function ()
        return SlipeServerVehicles.VehicleModel(502)
      end
      getHotringracer3 = function ()
        return SlipeServerVehicles.VehicleModel(503)
      end
      getMonster1 = function ()
        return SlipeServerVehicles.VehicleModel(444)
      end
      getMonster2 = function ()
        return SlipeServerVehicles.VehicleModel(556)
      end
      getMonster3 = function ()
        return SlipeServerVehicles.VehicleModel(557)
      end
      getMower = function ()
        return SlipeServerVehicles.VehicleModel(572)
      end
      getMrwhoopee = function ()
        return SlipeServerVehicles.VehicleModel(423)
      end
      getKart = function ()
        return SlipeServerVehicles.VehicleModel(571)
      end
      getTractor = function ()
        return SlipeServerVehicles.VehicleModel(531)
      end
      getTug = function ()
        return SlipeServerVehicles.VehicleModel(583)
      end
      getVortex = function ()
        return SlipeServerVehicles.VehicleModel(539)
      end
      getRcBandit = function ()
        return SlipeServerVehicles.VehicleModel(441)
      end
      getRcFlowerpot = function ()
        return SlipeServerVehicles.VehicleModel(594)
      end
      getRcTiger = function ()
        return SlipeServerVehicles.VehicleModel(564)
      end
      getClub = function ()
        return SlipeServerVehicles.VehicleModel(589)
      end
      getHuntley = function ()
        return SlipeServerVehicles.VehicleModel(579)
      end
      getLandstalker = function ()
        return SlipeServerVehicles.VehicleModel(400)
      end
      getMesa = function ()
        return SlipeServerVehicles.VehicleModel(500)
      end
      getPatriot = function ()
        return SlipeServerVehicles.VehicleModel(470)
      end
      getPerennial = function ()
        return SlipeServerVehicles.VehicleModel(404)
      end
      getRancher = function ()
        return SlipeServerVehicles.VehicleModel(489)
      end
      getRegina = function ()
        return SlipeServerVehicles.VehicleModel(479)
      end
      getRomero = function ()
        return SlipeServerVehicles.VehicleModel(442)
      end
      getSandking = function ()
        return SlipeServerVehicles.VehicleModel(495)
      end
      getSolair = function ()
        return SlipeServerVehicles.VehicleModel(458)
      end
      getStratum = function ()
        return SlipeServerVehicles.VehicleModel(561)
      end
      return {
        getAlpha = getAlpha,
        getBanshee = getBanshee,
        getBuffalo = getBuffalo,
        getBullet = getBullet,
        getCheetah = getCheetah,
        getComet = getComet,
        getElegy = getElegy,
        getEuros = getEuros,
        getFlash = getFlash,
        getInfernus = getInfernus,
        getJester = getJester,
        getPhoenix = getPhoenix,
        getSultan = getSultan,
        getSupergt = getSupergt,
        getTurismo = getTurismo,
        getUranus = getUranus,
        getWindsor = getWindsor,
        getZr350 = getZr350,
        getBlade = getBlade,
        getBroadway = getBroadway,
        getBuccaneer = getBuccaneer,
        getEsperanto = getEsperanto,
        getRemington = getRemington,
        getSavanna = getSavanna,
        getSlamvan = getSlamvan,
        getTornado = getTornado,
        getVoodoo = getVoodoo,
        getBlistacompact = getBlistacompact,
        getBravura = getBravura,
        getCadrona = getCadrona,
        getClover = getClover,
        getFeltzer = getFeltzer,
        getFortune = getFortune,
        getHermes = getHermes,
        getHustler = getHustler,
        getMajestic = getMajestic,
        getManana = getManana,
        getPrevion = getPrevion,
        getSabre = getSabre,
        getStallion = getStallion,
        getTampa = getTampa,
        getVirgo = getVirgo,
        getAdmiral = getAdmiral,
        getElegant = getElegant,
        getEmperor = getEmperor,
        getGlendale = getGlendale,
        getGreenwood = getGreenwood,
        getIntruder = getIntruder,
        getMerit = getMerit,
        getNebula = getNebula,
        getOceanic = getOceanic,
        getPremier = getPremier,
        getPrimo = getPrimo,
        getSentinel = getSentinel,
        getStafford = getStafford,
        getStretch = getStretch,
        getSunrise = getSunrise,
        getTahoma = getTahoma,
        getVincent = getVincent,
        getWashington = getWashington,
        getWillard = getWillard,
        getAmbulance = getAmbulance,
        getBarracks = getBarracks,
        getEnforcer = getEnforcer,
        getFbirancher = getFbirancher,
        getFbitruck = getFbitruck,
        getFiretruckladder = getFiretruckladder,
        getPolicecarls = getPolicecarls,
        getPolicecarlv = getPolicecarlv,
        getPolicecarsf = getPolicecarsf,
        getPoliceranger = getPoliceranger,
        getCementtruck = getCementtruck,
        getDft30 = getDft30,
        getDozer = getDozer,
        getDumper = getDumper,
        getDune = getDune,
        getFlatbed = getFlatbed,
        getForklift = getForklift,
        getLinerunner = getLinerunner,
        getPacker = getPacker,
        getRoadtrain = getRoadtrain,
        getSweeper = getSweeper,
        getTanker = getTanker,
        getTowtruck = getTowtruck,
        getTrashmaster = getTrashmaster,
        getUtilityvan = getUtilityvan,
        getBenson = getBenson,
        getBlackboxville = getBlackboxville,
        getBobcat = getBobcat,
        getBoxville = getBoxville,
        getMule = getMule,
        getPicador = getPicador,
        getSadler = getSadler,
        getSecuricar = getSecuricar,
        getWalton = getWalton,
        getYankee = getYankee,
        getYosemite = getYosemite,
        getBerkleysrcvan = getBerkleysrcvan,
        getBurrito = getBurrito,
        getCamper = getCamper,
        getJourney = getJourney,
        getMoonbeam = getMoonbeam,
        getNewsvan = getNewsvan,
        getPony = getPony,
        getRumpo = getRumpo,
        getBaggage = getBaggage,
        getBandito = getBandito,
        getBfinjection = getBfinjection,
        getBloodringbanger = getBloodringbanger,
        getBus = getBus,
        getCaddy = getCaddy,
        getCoach = getCoach,
        getCombineharvester = getCombineharvester,
        getHotdog = getHotdog,
        getHotknife = getHotknife,
        getHotringracer1 = getHotringracer1,
        getHotringracer2 = getHotringracer2,
        getHotringracer3 = getHotringracer3,
        getMonster1 = getMonster1,
        getMonster2 = getMonster2,
        getMonster3 = getMonster3,
        getMower = getMower,
        getMrwhoopee = getMrwhoopee,
        getKart = getKart,
        getTractor = getTractor,
        getTug = getTug,
        getVortex = getVortex,
        getRcBandit = getRcBandit,
        getRcFlowerpot = getRcFlowerpot,
        getRcTiger = getRcTiger,
        getClub = getClub,
        getHuntley = getHuntley,
        getLandstalker = getLandstalker,
        getMesa = getMesa,
        getPatriot = getPatriot,
        getPerennial = getPerennial,
        getRancher = getRancher,
        getRegina = getRegina,
        getRomero = getRomero,
        getSandking = getSandking,
        getSolair = getSolair,
        getStratum = getStratum
      }
    end)
    namespace.class("Boats", function (namespace)
      local getCoastguard, getDinghy, getJetmax, getLaunch, getMarquis, getPredator, getReefer, getSpeeder, 
      getSqualo, getTropic
      getCoastguard = function ()
        return SlipeServerVehicles.BoatModel(472)
      end
      getDinghy = function ()
        return SlipeServerVehicles.BoatModel(473)
      end
      getJetmax = function ()
        return SlipeServerVehicles.BoatModel(493)
      end
      getLaunch = function ()
        return SlipeServerVehicles.BoatModel(595)
      end
      getMarquis = function ()
        return SlipeServerVehicles.BoatModel(484)
      end
      getPredator = function ()
        return SlipeServerVehicles.BoatModel(430)
      end
      getReefer = function ()
        return SlipeServerVehicles.BoatModel(453)
      end
      getSpeeder = function ()
        return SlipeServerVehicles.BoatModel(452)
      end
      getSqualo = function ()
        return SlipeServerVehicles.BoatModel(446)
      end
      getTropic = function ()
        return SlipeServerVehicles.BoatModel(454)
      end
      return {
        getCoastguard = getCoastguard,
        getDinghy = getDinghy,
        getJetmax = getJetmax,
        getLaunch = getLaunch,
        getMarquis = getMarquis,
        getPredator = getPredator,
        getReefer = getReefer,
        getSpeeder = getSpeeder,
        getSqualo = getSqualo,
        getTropic = getTropic
      }
    end)
    namespace.class("Planes", function (namespace)
      local getAndromada, getAt400, getBeagle, getCropduster, getDodo, getHydra, getNevada, getRustler, 
      getShamal, getSkimmer, getStuntplane, getRcBaron
      getAndromada = function ()
        return SlipeServerVehicles.PlaneModel(592)
      end
      getAt400 = function ()
        return SlipeServerVehicles.PlaneModel(577)
      end
      getBeagle = function ()
        return SlipeServerVehicles.PlaneModel(511)
      end
      getCropduster = function ()
        return SlipeServerVehicles.PlaneModel(512)
      end
      getDodo = function ()
        return SlipeServerVehicles.PlaneModel(593)
      end
      getHydra = function ()
        return SlipeServerVehicles.PlaneModel(520)
      end
      getNevada = function ()
        return SlipeServerVehicles.PlaneModel(553)
      end
      getRustler = function ()
        return SlipeServerVehicles.PlaneModel(476)
      end
      getShamal = function ()
        return SlipeServerVehicles.PlaneModel(519)
      end
      getSkimmer = function ()
        return SlipeServerVehicles.PlaneModel(460)
      end
      getStuntplane = function ()
        return SlipeServerVehicles.PlaneModel(513)
      end
      getRcBaron = function ()
        return SlipeServerVehicles.PlaneModel(464)
      end
      return {
        getAndromada = getAndromada,
        getAt400 = getAt400,
        getBeagle = getBeagle,
        getCropduster = getCropduster,
        getDodo = getDodo,
        getHydra = getHydra,
        getNevada = getNevada,
        getRustler = getRustler,
        getShamal = getShamal,
        getSkimmer = getSkimmer,
        getStuntplane = getStuntplane,
        getRcBaron = getRcBaron
      }
    end)
    namespace.class("Helicopters", function (namespace)
      local getCargobob, getHunter, getLeviathan, getMaverick, getNewschopper, getPoliceMaverick, getRaindance, getSeasparrow, 
      getSparrow, getRcGoblin, getRcRaider
      getCargobob = function ()
        return SlipeServerVehicles.HelicopterModel(548)
      end
      getHunter = function ()
        return SlipeServerVehicles.HelicopterModel(425)
      end
      getLeviathan = function ()
        return SlipeServerVehicles.HelicopterModel(417)
      end
      getMaverick = function ()
        return SlipeServerVehicles.HelicopterModel(487)
      end
      getNewschopper = function ()
        return SlipeServerVehicles.HelicopterModel(488)
      end
      getPoliceMaverick = function ()
        return SlipeServerVehicles.HelicopterModel(497)
      end
      getRaindance = function ()
        return SlipeServerVehicles.HelicopterModel(563)
      end
      getSeasparrow = function ()
        return SlipeServerVehicles.HelicopterModel(447)
      end
      getSparrow = function ()
        return SlipeServerVehicles.HelicopterModel(469)
      end
      getRcGoblin = function ()
        return SlipeServerVehicles.HelicopterModel(501)
      end
      getRcRaider = function ()
        return SlipeServerVehicles.HelicopterModel(465)
      end
      return {
        getCargobob = getCargobob,
        getHunter = getHunter,
        getLeviathan = getLeviathan,
        getMaverick = getMaverick,
        getNewschopper = getNewschopper,
        getPoliceMaverick = getPoliceMaverick,
        getRaindance = getRaindance,
        getSeasparrow = getSeasparrow,
        getSparrow = getSparrow,
        getRcGoblin = getRcGoblin,
        getRcRaider = getRcRaider
      }
    end)
    namespace.class("Trailers", function (namespace)
      local getBaggageCovered, getBaggageUncovered, getSteps, getFarmtrailer, getStreetcleaner, getGasSemi, getSemi, getOpenSemi, 
      getSmallSemi
      getBaggageCovered = function ()
        return SlipeServerVehicles.TrailerModel(606)
      end
      getBaggageUncovered = function ()
        return SlipeServerVehicles.TrailerModel(607)
      end
      getSteps = function ()
        return SlipeServerVehicles.TrailerModel(608)
      end
      getFarmtrailer = function ()
        return SlipeServerVehicles.TrailerModel(610)
      end
      getStreetcleaner = function ()
        return SlipeServerVehicles.TrailerModel(611)
      end
      getGasSemi = function ()
        return SlipeServerVehicles.TrailerModel(584)
      end
      getSemi = function ()
        return SlipeServerVehicles.TrailerModel(435)
      end
      getOpenSemi = function ()
        return SlipeServerVehicles.TrailerModel(450)
      end
      getSmallSemi = function ()
        return SlipeServerVehicles.TrailerModel(591)
      end
      return {
        getBaggageCovered = getBaggageCovered,
        getBaggageUncovered = getBaggageUncovered,
        getSteps = getSteps,
        getFarmtrailer = getFarmtrailer,
        getStreetcleaner = getStreetcleaner,
        getGasSemi = getGasSemi,
        getSemi = getSemi,
        getOpenSemi = getOpenSemi,
        getSmallSemi = getSmallSemi
      }
    end)
    namespace.class("Trains", function (namespace)
      local getFreightEngine, getBoxFreight, getFlatFreight, getBrownStreakEngine, getBrownStreakCarriage, getTrolly
      getFreightEngine = function ()
        return SlipeServerVehicles.TrainModel(537)
      end
      getBoxFreight = function ()
        return SlipeServerVehicles.TrainModel(590)
      end
      getFlatFreight = function ()
        return SlipeServerVehicles.TrainModel(569)
      end
      getBrownStreakEngine = function ()
        return SlipeServerVehicles.TrainModel(538)
      end
      getBrownStreakCarriage = function ()
        return SlipeServerVehicles.TrainModel(570)
      end
      getTrolly = function ()
        return SlipeServerVehicles.TrainModel(449)
      end
      return {
        getFreightEngine = getFreightEngine,
        getBoxFreight = getBoxFreight,
        getFlatFreight = getFlatFreight,
        getBrownStreakEngine = getBrownStreakEngine,
        getBrownStreakCarriage = getBrownStreakCarriage,
        getTrolly = getTrolly
      }
    end)
    namespace.class("TurretedVehicles", function (namespace)
      local getRhino, getSwat, getFiretruck
      getRhino = function ()
        return SlipeServerVehicles.TurretedModel(432)
      end
      getSwat = function ()
        return SlipeServerVehicles.TurretedModel(601)
      end
      getFiretruck = function ()
        return SlipeServerVehicles.TurretedModel(407)
      end
      return {
        getRhino = getRhino,
        getSwat = getSwat,
        getFiretruck = getFiretruck
      }
    end)
    namespace.class("Taxis", function (namespace)
      local getCabbie, getTaxi
      getCabbie = function ()
        return SlipeServerVehicles.TaxiModel(438)
      end
      getTaxi = function ()
        return SlipeServerVehicles.TaxiModel(420)
      end
      return {
        getCabbie = getCabbie,
        getTaxi = getTaxi
      }
    end)
    __ctor__ = function (this, id)
      SlipeSharedVehicles.SharedVehicleModel.__ctor__(this, id)
    end
    getHandling = function (this)
      return SlipeServerVehicles.ModelHandling(this.Id)
    end
    getVehicles = function (this)
      local mtaElements = SlipeMtaDefinitions.MtaShared.GetArrayFromTable(SlipeMtaDefinitions.MtaServer.GetVehiclesOfType(this.Id), "MTAElement", T)
      return SlipeSharedElements.ElementManager.getInstance():CastArray(mtaElements, SlipeServerVehicles.BaseVehicle)
    end
    -- <summary>
    -- Get a vehicle model from the model name as a string, instantiated as the right model class
    -- </summary>
    -- <returns>The Vehicle model, instantiated as the right model class</returns>
    FromName = function (name)
      return FromId(SlipeMtaDefinitions.MtaShared.GetVehicleModelFromName(name))
    end
    -- <summary>
    -- Get a vehicle model from its ID, instantiated as the right model class
    -- </summary>
    -- <returns>The Vehicle model, instantiated as the right model class</returns>
    FromId = function (id)
      if Linq.Contains(SlipeSharedVehicles.SharedVehicleModel.boatModels, id) then
        return SlipeServerVehicles.BoatModel(id)
      end
      if Linq.Contains(SlipeSharedVehicles.SharedVehicleModel.planeModels, id) then
        return SlipeServerVehicles.PlaneModel(id)
      end
      if Linq.Contains(SlipeSharedVehicles.SharedVehicleModel.helicopterModels, id) then
        return SlipeServerVehicles.HelicopterModel(id)
      end
      if Linq.Contains(SlipeSharedVehicles.SharedVehicleModel.trailerModels, id) then
        return SlipeServerVehicles.TrailerModel(id)
      end
      if Linq.Contains(SlipeSharedVehicles.SharedVehicleModel.trainModels, id) then
        return SlipeServerVehicles.TrainModel(id)
      end
      if Linq.Contains(SlipeSharedVehicles.SharedVehicleModel.turretedModels, id) then
        return SlipeServerVehicles.TurretedModel(id)
      end
      if Linq.Contains(SlipeSharedVehicles.SharedVehicleModel.taxiModels, id) then
        return SlipeServerVehicles.TaxiModel(id)
      end

      return class(id)
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Vehicles.SharedVehicleModel
        }
      end,
      getHandling = getHandling,
      getVehicles = getVehicles,
      FromName = FromName,
      FromId = FromId,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
