-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnAcInfoEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, detectedAcList, d3d9Size, d3d9Md5, d3d9Sha256)
      this.DetectedAcList = SlipeMtaDefinitions.MtaShared.GetArrayFromTable(detectedAcList, "System.String", System.String)
      this.D3d9Size = System.cast(System.Int32, d3d9Size)
      this.D3d9Md5 = System.cast(System.String, d3d9Md5)
      this.D3d9Sha256 = System.cast(System.String, d3d9Sha256)
    end
    return {
      D3d9Size = 0,
      __ctor__ = __ctor__
    }
  end)
end)
