-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SlipeSharedIO
local SystemNumerics
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedIO = Slipe.Shared.IO
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnClickEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, mouseButton, buttonState, clickedElement, wx, wy, wz, sx, sy)
      this.WorldPosition = System.default(SystemNumerics.Vector3)
      this.ScreenPosition = System.default(SystemNumerics.Vector2)
      this.MouseButton = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedIO.MouseButton), System.cast(System.String, mouseButton)))
      this.MouseButtonState = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedIO.MouseButtonState), System.cast(System.String, buttonState)))
      this.ClickedElement = SlipeSharedElements.ElementManager.getInstance():GetElement(clickedElement, SlipeSharedElements.PhysicalElement)
      this.WorldPosition = SystemNumerics.Vector3(System.cast(System.Single, wx), System.cast(System.Single, wy), System.cast(System.Single, wz))
      this.ScreenPosition = SystemNumerics.Vector2(System.cast(System.Single, sx), System.cast(System.Single, sy))
    end
    return {
      MouseButton = 0,
      MouseButtonState = 0,
      __ctor__ = __ctor__
    }
  end)
end)
