-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnCommandEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, command)
      this.Command = System.cast(System.String, command)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
