-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnModInfoEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, fileName, items)
      this.FileName = System.cast(System.String, fileName)
      this.Items = items
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
