-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnNetworkInteruptionEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, status, ticksSinceInteruptionStarted)
      this.Status = System.cast(System.Int32, status)
      this.Ticks = System.cast(System.Int32, ticksSinceInteruptionStarted)
    end
    return {
      Status = 0,
      Ticks = 0,
      __ctor__ = __ctor__
    }
  end)
end)
