-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnNicknameChangedEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, oldNickname, newNickname, changedByuser)
      this.OldNickname = System.cast(System.String, oldNickname)
      this.NewNickname = System.cast(System.String, newNickname)
      this.IsChangedByUser = System.cast(System.Boolean, changedByuser)
    end
    return {
      IsChangedByUser = false,
      __ctor__ = __ctor__
    }
  end)
end)
