-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerPickups
local SlipeSharedElements
System.import(function (out)
  SlipeServerPickups = Slipe.Server.Pickups
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnPickupLeaveEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, pickup)
      this.Pickup = SlipeSharedElements.ElementManager.getInstance():GetElement(pickup, SlipeServerPickups.Pickup)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
