-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerPeds
local SlipeSharedElements
local SlipeSharedPeds
System.import(function (out)
  SlipeServerPeds = Slipe.Server.Peds
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedPeds = Slipe.Shared.Peds
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnQuitEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, quitType, reason, responsiblePlayer)
      this.QuitType = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedPeds.QuitType), System.cast(System.String, quitType)))
      this.Reason = System.cast(System.String, reason)
      this.ResponsiblePlayer = SlipeSharedElements.ElementManager.getInstance():GetElement(responsiblePlayer, SlipeServerPeds.Player)
    end
    return {
      QuitType = 0,
      __ctor__ = __ctor__
    }
  end)
end)
