-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerResources
System.import(function (out)
  SlipeServerResources = Slipe.Server.Resources
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnScreenShotEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, resource, status, imageData, timeStamp, tag)
      this.Resource = SlipeServerResources.Resource.Get1(resource)
      this.Status = System.cast(System.Int32, status)
      this.ImageData = System.cast(System.String, imageData)
      this.TimeStamp = System.cast(System.Int32, timeStamp)
      this.Tag = System.cast(System.String, tag)
    end
    return {
      Status = 0,
      TimeStamp = 0,
      __ctor__ = __ctor__
    }
  end)
end)
