-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerPeds
local SlipeSharedElements
System.import(function (out)
  SlipeServerPeds = Slipe.Server.Peds
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnStealthKillEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, victim)
      this.Victim = SlipeSharedElements.ElementManager.getInstance():GetElement(victim, SlipeServerPeds.Ped)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
