-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnTargetEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, target)
      this.Target = SlipeSharedElements.ElementManager.getInstance():GetElement(target, SlipeSharedElements.PhysicalElement)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
