-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnUnmutedEventArgs", function (namespace)
    return {}
  end)
end)
