-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerPeds
local SlipeServerVehicles
local SlipeSharedElements
System.import(function (out)
  SlipeServerPeds = Slipe.Server.Peds
  SlipeServerVehicles = Slipe.Server.Vehicles
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnVehicleEnterEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, vehicle, seat, jacked)
      this.Vehicle = SlipeSharedElements.ElementManager.getInstance():GetElement(vehicle, SlipeServerVehicles.BaseVehicle)
      this.Seat = System.cast(System.Int32, seat)
      this.JackedPlayer = SlipeSharedElements.ElementManager.getInstance():GetElement(jacked, SlipeServerPeds.Player)
    end
    return {
      Seat = 0,
      __ctor__ = __ctor__
    }
  end)
end)
