-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerWeapons
System.import(function (out)
  SlipeServerWeapons = Slipe.Server.Weapons
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnWeaponSwitchEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, previousWeapon, newWeapon)
      this.PreviousWeapon = System.new(SlipeServerWeapons.WeaponModel, 2, System.cast(System.Int32, previousWeapon))
      this.NewWeapon = System.new(SlipeServerWeapons.WeaponModel, 2, System.cast(System.Int32, newWeapon))
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
