-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerAccounts
System.import(function (out)
  SlipeServerAccounts = Slipe.Server.Accounts
end)
System.namespace("Slipe.Server.Accounts.Events", function (namespace)
  namespace.class("OnDataChangeEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, account, key, value)
      this.Account = SlipeServerAccounts.Account.Get(account)
      this.Key = System.cast(System.String, key)
      this.Value = System.cast(System.String, value)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
