-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Game.Events", function (namespace)
  namespace.class("OnPlayerConnectEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, nickname, ip, username, serial, versionNumber, versionString)
      this.Nickname = System.cast(System.String, nickname)
      this.Ip = System.cast(System.String, ip)
      this.Username = System.cast(System.String, username)
      this.Serial = System.cast(System.String, serial)
      this.VersionNumber = System.cast(System.Int32, versionNumber)
      this.VersionString = System.cast(System.String, versionString)
    end
    return {
      VersionNumber = 0,
      __ctor__ = __ctor__
    }
  end)
end)
