-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Game.Events", function (namespace)
  namespace.class("OnSettingChangeEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, setting, oldValue, newValue)
      this.Setting = System.cast(System.String, setting)
      this.OldValue = System.cast(System.String, oldValue)
      this.NewValue = System.cast(System.String, newValue)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
