-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerVehicles
local SlipeSharedElements
System.import(function (out)
  SlipeServerVehicles = Slipe.Server.Vehicles
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Vehicles.Events", function (namespace)
  namespace.class("OnAttachEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, truck)
      this.Truck = SlipeSharedElements.ElementManager.getInstance():GetElement(truck, SlipeServerVehicles.Vehicle)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
