-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerPeds
local SlipeSharedElements
System.import(function (out)
  SlipeServerPeds = Slipe.Server.Peds
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Vehicles.Events", function (namespace)
  namespace.class("OnExitEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, player, seat, jacker, forcedByScript)
      this.Player = SlipeSharedElements.ElementManager.getInstance():GetElement(player, SlipeServerPeds.Player)
      this.Seat = System.cast(System.Int32, seat)
      this.Jacker = SlipeSharedElements.ElementManager.getInstance():GetElement(jacker, SlipeServerPeds.Player)
      this.IsForced = System.cast(System.Boolean, forcedByScript)
    end
    return {
      Seat = 0,
      IsForced = false,
      __ctor__ = __ctor__
    }
  end)
end)
