-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Vehicles.Events", function (namespace)
  namespace.class("OnExplodeEventArgs", function (namespace)
    return {}
  end)
end)
