-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Vehicles.Events", function (namespace)
  namespace.class("OnRespawnEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, exploded)
      this.IsExploded = System.cast(System.Boolean, exploded)
    end
    return {
      IsExploded = false,
      __ctor__ = __ctor__
    }
  end)
end)
