-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Exports", function (namespace)
  namespace.class("ExportAttribute", function (namespace)
    return {
      __inherits__ = function (out)
        return {
          System.Attribute
        }
      end
    }
  end)
end)
