-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SlipeSharedIO
local SlipeSharedPeds
local SystemNumerics
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedIO = Slipe.Shared.IO
  SlipeSharedPeds = Slipe.Shared.Peds
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Shared.Elements.Events", function (namespace)
  namespace.class("OnClickedEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, mouseButton, buttonState, clickedBy, x, y, z)
      this.Position = System.default(SystemNumerics.Vector3)
      this.MouseButton = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedIO.MouseButton), System.cast(System.String, mouseButton)))
      this.MouseButtonState = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedIO.MouseButtonState), System.cast(System.String, mouseButton)))
      this.Player = SlipeSharedElements.ElementManager.getInstance():GetElement(clickedBy, SlipeSharedPeds.SharedPed)
      this.Position = SystemNumerics.Vector3(System.cast(System.Single, x), System.cast(System.Single, y), System.cast(System.Single, z))
    end
    return {
      MouseButton = 0,
      MouseButtonState = 0,
      __ctor__ = __ctor__
    }
  end)
end)
