-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedCollisionShapes
local SlipeSharedElements
System.import(function (out)
  SlipeSharedCollisionShapes = Slipe.Shared.CollisionShapes
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Shared.Elements.Events", function (namespace)
  namespace.class("OnCollisionShapeHitEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, colshape, matchingDimension)
      this.CollisionShape = SlipeSharedElements.ElementManager.getInstance():GetElement(colshape, SlipeSharedCollisionShapes.CollisionShape)
      this.IsDimensionMatching = System.cast(System.Boolean, matchingDimension)
    end
    return {
      IsDimensionMatching = false,
      __ctor__ = __ctor__
    }
  end)
end)
