-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Elements.Events", function (namespace)
  namespace.class("OnModelChangeEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, oldModel, newModel)
      this.OldModel = System.cast(System.Int32, oldModel)
      this.NewModel = System.cast(System.Int32, newModel)
    end
    return {
      OldModel = 0,
      NewModel = 0,
      __ctor__ = __ctor__
    }
  end)
end)
