-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Elements.Events", function (namespace)
  namespace.class("OnSteamOutEventArgs", function (namespace)
    return {}
  end)
end)
