-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SlipeSharedPeds
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedPeds = Slipe.Shared.Peds
end)
System.namespace("Slipe.Shared.Elements.Events", function (namespace)
  namespace.class("OnStartSyncEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, newSyncer)
      this.NewSyncer = SlipeSharedElements.ElementManager.getInstance():GetElement(newSyncer, SlipeSharedPeds.SharedPed)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
