-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Pickups.Events", function (namespace)
  namespace.class("OnSpawnEventArgs", function (namespace)
    return {}
  end)
end)
