-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Shared.CollisionShapes.Events", function (namespace)
  namespace.class("OnHitEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, element, matchingDimension)
      this.Element = SlipeSharedElements.ElementManager.getInstance():GetElement(element, SlipeSharedElements.PhysicalElement)
      this.IsDimensionMatching = System.cast(System.Boolean, matchingDimension)
    end
    return {
      IsDimensionMatching = false,
      __ctor__ = __ctor__
    }
  end)
end)
