-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.IO.Events", function (namespace)
  namespace.class("OnChatMessageEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, message)
      this.Message = System.cast(System.String, message)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
